<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">concatTwoDocs</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewoKCUlEYXRhIGlu
cHV0RG9jMSA9IElEYXRhVXRpbC5nZXRJRGF0YShpZGMsICJEb2MxIik7CglJRGF0YSBpbnB1dERv
YzIgPSBJRGF0YVV0aWwuZ2V0SURhdGEoaWRjLCAiRG9jMiIpOwoKCWlmICgoaW5wdXREb2MxID09
IG51bGwpICYmIChpbnB1dERvYzIgPT0gbnVsbCkpIHJldHVybjsKCglpZiAoKGlucHV0RG9jMSAh
PSBudWxsKSAmJiAoaW5wdXREb2MyICE9IG51bGwpKSB7CgkJSURhdGFVdGlsLmFwcGVuZChpbnB1
dERvYzEsIGlucHV0RG9jMik7CgkJSURhdGFVdGlsLnB1dChpZGMsImZpbmFsRG9jIixpbnB1dERv
YzIpOwoKCX0gZWxzZSBpZiAoaW5wdXREb2MxICE9IG51bGwpIHsKCQlJRGF0YVV0aWwucHV0KGlk
YywgImZpbmFsRG9jIiwgaW5wdXREb2MxKTsKCgl9IGVsc2UJaWYgKGlucHV0RG9jMiAhPSBudWxs
KSB7CgkJSURhdGFVdGlsLnB1dChpZGMsICJmaW5hbERvYyIsIGlucHV0RG9jMik7Cgl9CgoKfSBj
YXRjaCAoRXhjZXB0aW9uIGV4YykgewoJU2VydmVyQVBJLmxvZ0Vycm9yKGV4Yyk7Cgl0aHJvdyBu
ZXcgU2VydmljZUV4Y2VwdGlvbihleGMudG9TdHJpbmcoKSk7Cn0KCmlkYy5kZXN0cm95KCk7</value>
</Values>
