---
# In this file users, backendroles and hosts can be mapped to Search Guard roles.
# Permissions for Search Guard roles are configured in sg_roles.yml

_sg_meta:
  type: "rolesmapping"
  config_version: 2

# Define your roles mapping here
# See https://docs.search-guard.com/latest/mapping-users-roles

## Demo roles mapping

SGS_ALL_ACCESS:
  reserved: true
  backend_roles:
  - "admin"
  description: "Maps admin to SGS_ALL_ACCESS"
