<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">encodeIDataToXmlStr</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGEJ
aW5wdXRPZklEYXRhID0gSURhdGFVdGlsLmdldElEYXRhKCBwaXBlbGluZUN1cnNvciwgImlucHV0
T2ZJRGF0YSIgKTsKCmlmICggaW5wdXRPZklEYXRhICE9IG51bGwpewoJSURhdGFYTUxDb2RlciBp
RGF0YVhtbENvZGVyID0gbmV3IElEYXRhWE1MQ29kZXIoKSA7Cgl0cnl7CgkJYnl0ZVtdIGJpdGVz
ID0gaURhdGFYbWxDb2Rlci5lbmNvZGVUb0J5dGVzKGlucHV0T2ZJRGF0YSk7CgkJSURhdGFVdGls
LnB1dCggcGlwZWxpbmVDdXJzb3IsICJpRGF0YVhtbFN0ciIsIG5ldyBTdHJpbmcoYml0ZXMpICk7
CQoJfWNhdGNoKEV4Y2VwdGlvbiBlKXsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsK
CX1maW5hbGx5ewoJCXBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCX0KfQoKCg==</value>
</Values>
