<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">sortDocList</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhW10gaW5MaXN0ID0g
bnVsbDsKSURhdGFbXSBvdXRMaXN0ID0gbnVsbDsKU3RyaW5nIGtleSA9IG51bGw7CmJvb2xlYW4g
c29ydERlc2NlbmRpbmcgPSB0cnVlOwoKdHJ5IHsKCWluTGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0
YUFycmF5KGlkYywgImlucHV0RG9jTGlzdCIpOwoKCWlmIChpbkxpc3QgPT0gbnVsbCkgewoJCXJl
dHVybjsKCX0KCglrZXkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlkYywgImtleSIpOwoJaWYgKGlk
Yy5maXJzdCgic29ydERlc2NlbmRpbmciKSkgewoJCXNvcnREZXNjZW5kaW5nID0gSURhdGFVdGls
LmdldEJvb2xlYW4oaWRjLCAic29ydERlc2NlbmRpbmciKTsKCX0KCglpZiAoaW5MaXN0Lmxlbmd0
aCA+IDApIHsKCQlvdXRMaXN0ID0gaW5MaXN0OwoJCUlEYXRhVXRpbC5zb3J0SURhdGFBcnJheUJ5
S2V5KG91dExpc3QsIGtleSwgSURhdGFVdGlsLkNPTVBBUkVfVFlQRV9DT0xMQVRJT04sIG51bGws
IHNvcnREZXNjZW5kaW5nKTsKCX0KCn0gY2F0Y2ggKEV4Y2VwdGlvbiBleGMpIHsKCVNlcnZlckFQ
SS5sb2dFcnJvcihleGMpOwoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZXhjLnRvU3RyaW5n
KCkpOwp9IGZpbmFsbHkgewoJSURhdGFVdGlsLnB1dChpZGMsICJvdXRwdXREb2NMaXN0Iiwgb3V0
TGlzdCk7CglpZGMuZGVzdHJveSgpOwp9</value>
</Values>
