<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">makeDir</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nCWRpciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAi
ZGlyIiApOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CmludCB4ID0gMDsKIAp0cnl7CiAKCUZp
bGUgZGlyUGF0aCA9IG5ldyBGaWxlKGRpcik7CgoJd2hpbGUodHJ1ZSl7CgoJCWlmKCB4ID4gMyAp
IGJyZWFrOwoKCQlpZiAoIGRpclBhdGguZXhpc3RzKCkgKSB7IAoJCQlicmVhazsKCQl9CgkJZWxz
ZSB7CgkJICAgIGlmICggZGlyUGF0aC5ta2RpcnMoKSApewoJCQkJYnJlYWs7CgkJCX0gZWxzZSB7
fQoJCX0KCQlUaHJlYWQuc2xlZXAoMjAwMCk7CgkJCgkJeCsrOwoJfQp9CmNhdGNoKEV4Y2VwdGlv
biBlKXt9Cg==</value>
</Values>
