<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listFilesWithRegexFilter</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCg0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNClN0cmluZwlkaXJlY3RvcnkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGlu
ZUN1cnNvciwgImRpcmVjdG9yeSIgKTsNClN0cmluZwlmaWx0ZXIgPSBJRGF0YVV0aWwuZ2V0U3Ry
aW5nKCBwaXBlbGluZUN1cnNvciwgImZpbHRlciIgKTsNCkZpbGUgZGlyID0gbmV3IEZpbGUoZGly
ZWN0b3J5KTsNCmlmICghIGRpci5leGlzdHMoKSB8fCBkaXIuaXNGaWxlKCkpew0KCXRocm93IG5l
dyBTZXJ2aWNlRXhjZXB0aW9uKCJEaXJlY3RvcnkgIiArIGRpcmVjdG9yeSArICIgZG9lcyBub3Qg
ZXhpc3QuIik7DQp9DQppZihmaWx0ZXIgPT0gbnVsbCB8fCBmaWx0ZXIudHJpbSgpLmVxdWFscygi
Iikpew0KCVN0cmluZyBmaWxlc1tdID0gZGlyLmxpc3QoKTsNCglJRGF0YVV0aWwucHV0KCBwaXBl
bGluZUN1cnNvciwgImZpbGVMaXN0IiwgZmlsZXMpOw0KCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5l
Q3Vyc29yLCAibnVtRmlsZXMiLCBmaWxlcy5sZW5ndGgpOw0KfSBlbHNlIHsNCglTdHJpbmcgZmls
ZXNbXSA9IGRpci5saXN0KG5ldyBSZWdleEZpbGVOYW1lRmlsdGVyKGZpbHRlcikpOw0KCUlEYXRh
VXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAiZmlsZUxpc3QiLCBmaWxlcyk7DQoJSURhdGFVdGls
LnB1dCggcGlwZWxpbmVDdXJzb3IsICJudW1GaWxlcyIsIGZpbGVzLmxlbmd0aCk7DQp9DQpwaXBl
bGluZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
