<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">truncateString</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyBrZXlGaWx0ZXIg
PSBudWxsOwpTdHJpbmcgaW5TdHJpbmcgPSBudWxsOwpTdHJpbmcgdHJ1bmMgPSBudWxsOwpTdHJp
bmcgcmVzdWx0ID0gbnVsbDsKCnRyeSB7CgkKCWluU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmlu
ZyhpZGMsICJpblN0cmluZyIpOwoKCWlmIChpblN0cmluZyA9PSBudWxsKSB7CgkJcmV0dXJuOwoJ
fQoJCglrZXlGaWx0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlkYywgImtleUZpbHRlciIpOwoJ
dHJ1bmMgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlkYywgInRydW5jIik7CglpbnQgaW5TdHJpbmds
ZW4gPSBpblN0cmluZy5sZW5ndGgoKTsKCWludCBrZXlQb3NpdGlvbiA9IGluU3RyaW5nLmluZGV4
T2Yoa2V5RmlsdGVyKTsKCgkvL0RlYnVnLmxvZygxLCJ0cnVuYyA6ICIgKyB0cnVuYyArICIgaW5T
dHJpbmdsZW4gOiAiICsgaW5TdHJpbmdsZW4gKyAiIGtleVBvc2l0aW9uOiAiICsga2V5UG9zaXRp
b24pOwoKCWlmIChrZXlQb3NpdGlvbiA8IDApIHsKCQlyZXN1bHQgPSBpblN0cmluZzsKCQlyZXR1
cm47Cgl9CgoJaWYgKHRydW5jLmVxdWFscygibGVmdCIpKSB7CgkJcmVzdWx0ID0gaW5TdHJpbmcu
c3Vic3RyaW5nKGtleVBvc2l0aW9uLCBpblN0cmluZ2xlbik7Cgl9IGVsc2UgaWYgKHRydW5jLmVx
dWFscygicmlnaHQiKSkgewoJCXJlc3VsdCA9IGluU3RyaW5nLnN1YnN0cmluZygwLGtleVBvc2l0
aW9uKTsKCX0KCn0gY2F0Y2ggKEV4Y2VwdGlvbiBleGMpIHsKCVNlcnZlckFQSS5sb2dFcnJvcihl
eGMpOwoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZXhjLnRvU3RyaW5nKCkpOwp9IGZpbmFs
bHkgewoJSURhdGFVdGlsLnB1dChpZGMsICJ2YWx1ZSIsIHJlc3VsdCk7CglpZGMuZGVzdHJveSgp
Owp9</value>
</Values>
