<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringToBoolean</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwkJDQpTdHJpbmcgaW5TdHJpbmcg
PSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGMsICJpblN0cmluZyIpOw0KDQppZiAoaW5TdHJpbmcgPT0g
bnVsbCB8fCBpblN0cmluZy5lcXVhbHMoIiIpKXsNCgkvL2RvIG5vdGhpbmcNCn0gZWxzZSB7DQoJ
U3RyaW5nIHRlbXAgPSBpblN0cmluZy50cmltKCkudG9Mb3dlckNhc2UoKTsNCglpZiAodGVtcC5l
cXVhbHMoInRydWUiKSApew0KCQlJRGF0YVV0aWwucHV0KGMsICJvdXRCb29sZWFuIiwgbmV3IEJv
b2xlYW4odHJ1ZSkpOw0KCX0gZWxzZSBpZih0ZW1wLmVxdWFscygiZmFsc2UiKSl7DQoJCUlEYXRh
VXRpbC5wdXQoYywgIm91dEJvb2xlYW4iLCBuZXcgQm9vbGVhbihmYWxzZSkpOw0KCX0gZWxzZXsN
CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oInVua25vdyBib29sZWFuIHZhbHVlICIgKyBp
blN0cmluZyk7DQoJfQkJCQ0KfQ0KDQpjLmRlc3Ryb3koKTs=</value>
</Values>
