<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">moveFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgLSBpbiAKSURhdGFDdXJzb3IgcGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsK
U3RyaW5nCW1vdmVGcm9tID0gSURhdGFVdGlsLmdldFN0cmluZyggcGMsICJtb3ZlRnJvbSIgKTsK
U3RyaW5nCW1vdmVUbyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBjLCAibW92ZVRvIiApOwpGaWxl
IGYsIHQgPSBudWxsOyAKYm9vbGVhbiByZXN1bHQ7ClN0cmluZyBzdGF0dXMgPSAiRkFJTEVEIjsK
CnRyeXsKCWYgPSBuZXcgRmlsZShtb3ZlRnJvbSk7CS8vIHNvdXJjZSBmaWxlCgl0ID0gbmV3IEZp
bGUobW92ZVRvKTsJLy8gdGFyZ2V0IGZpbGUKCQoJaWYoZi5leGlzdHMoKSl7CQkJLy8gY2hlY2sg
d2hldGhlciBzb3VyY2UgZmlsZSBleGlzdHMKCQlpZih0LmV4aXN0cygpKXsJCS8vIGNoZWNrIHdo
ZXRoZXIgdGFyZ2V0IGZpbGUgZXhpc3RzCgkJCXN0YXR1cyA9ICJGaWxlIGFscmVhZHkgZXhpc3Rz
IGluIHRhcmdldCBkaXJlY3RvcnkhIjsKCQl9CgkJZWxzZXsKCQkJaWYoZi5yZW5hbWVUbyggdCAp
KQkvLyBjaGVjayB3aGV0aGVyIG1vdmluZyBmaWxlIHdhcyBzdWNjZXNzZnVsCgkJCQlzdGF0dXMg
PSAiT0siOwoJCX0KCX0KCWVsc2V7CgkJc3RhdHVzID0gZiArICIgZG9lcyBub3QgZXhpc3QhIjsK
CX0KfQpjYXRjaChFeGNlcHRpb24gZSl7CgkvLyBkbyBub3RoaW5nCglzdGF0dXMgPSBlLnRvU3Ry
aW5nKCk7Cn0KCgovLyBwaXBlbGluZSAtIG91dApJRGF0YVV0aWwucHV0KCBwYywgInN0YXR1cyIs
IHN0YXR1cyApOwpwYy5kZXN0cm95KCk7Cg==</value>
</Values>
