# This docker-compose file is an example for a setup with an API Gateway cluster with three containers, an Elasticsearch cluster with three containers and a Terracotta container.
# The image names of API Gateway and Terracotta can be set by modifying the .env file when the file is in the working directory or by setting the environment variable APIGW_DOCKER_IMAGE_NAME and TERRACOTTA_DOCKER_IMAGE_NAME.
# To use this file run: docker-compose -f apigw-elasticsearch-cluster.yml up
# Append -d to run it in detached mode.
# To stop and remove containers, networks, volumes and images created by up run: docker-compose -f apigw-elasticsearch-cluster.yml down
version: '3.5'
services:
  terracotta:
    # Image name
    image: ${TERRACOTTA_DOCKER_IMAGE_NAME}
    # Container name
    container_name: terracotta
    # Setting for exposing ports to the outside (external port:internal port).
    ports:
      - 9510:9510
    # Needs to be the same network for all containers.
    networks:
      - api-gateway-network
  apigateway1:
    image: ${APIGW_DOCKER_IMAGE_NAME}
    container_name: api-gateway-01
    environment:
      # Name and port of the Terracotta container.
      - apigw_cluster_tsaUrls=terracotta:9510
      # License file name for Terracotta.
      - apigw_terracotta_license_filename=terracotta-license.key
      # Name and port of the REST interface of an Elasticsearch container
      # Or a loadbalancer which directs to the REST interace of the Elasticsearch containers.
      - apigw_elasticsearch_hosts=elasticsearch:9200
      # HTTPS enablement.
      - apigw_elasticsearch_https_enabled=false
      # Username and password for Elasticsearch. As standard leave it blank.
      - apigw_elasticsearch_http_username=
      - apigw_elasticsearch_http_password=
    ports:
      # Server port
      - 5555:5555
      # UI port
      - 9072:9072
    networks:
      - api-gateway-network
  apigateway2:
    image: ${APIGW_DOCKER_IMAGE_NAME}
    container_name: api-gateway-02
    environment:
      - apigw_cluster_tsaUrls=terracotta:9510
      - apigw_terracotta_license_filename=terracotta-license.key
      - apigw_elasticsearch_hosts=elasticsearch:9200
      - apigw_elasticsearch_https_enabled=false
      - apigw_elasticsearch_http_username=
      - apigw_elasticsearch_http_password=
    ports:
      - 5556:5555
      - 9073:9072
    networks:
      - api-gateway-network
  apigateway3:
    image: ${APIGW_DOCKER_IMAGE_NAME}
    container_name: api-gateway-03
    environment:
      - apigw_cluster_tsaUrls=terracotta:9510
      - apigw_terracotta_license_filename=terracotta-license.key
      - apigw_elasticsearch_hosts=elasticsearch:9200
      - apigw_elasticsearch_https_enabled=false
      - apigw_elasticsearch_http_username=
      - apigw_elasticsearch_http_password=
    ports:
      - 5557:5555
      - 9074:9072
    networks:
      - api-gateway-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    # Elasticsearch settings
    environment:
      # Important when you have several Elasticsearch containers. They need to be in the same network. Should be a different name than in other environments.
      - cluster.name=SAG_EventDataStore
      # The node name. Used for inital master node discovery.
      - node.name=elasticsearch
      # For discovery of all Elasticsearch containers.
      - discovery.seed_hosts=elasticsearch:9300,elasticsearch2:9300,elasticsearch3:9300
      # Used for cluster bootstrapping. The mentioned nodes are potential master nodes.
      - cluster.initial_master_nodes=elasticsearch,elasticsearch2,elasticsearch3
    ports:
      # REST interface
      - 9240:9200
      # Nodes communication
      - 9340:9300
    networks:
      - api-gateway-network
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch2
    environment:
      - cluster.name=SAG_EventDataStore
      - node.name=elasticsearch2
      - discovery.seed_hosts=elasticsearch:9300,elasticsearch2:9300,elasticsearch3:9300
      - cluster.initial_master_nodes=elasticsearch,elasticsearch2,elasticsearch3
    networks:
      - api-gateway-network
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch3
    environment:
      - cluster.name=SAG_EventDataStore
      - node.name=elasticsearch3
      - discovery.seed_hosts=elasticsearch:9300,elasticsearch2:9300,elasticsearch3:9300
      - cluster.initial_master_nodes=elasticsearch,elasticsearch2,elasticsearch3
    networks:
      - api-gateway-network
networks:
  api-gateway-network:
    # For setting a specific network name.
    name: api-gateway-network