# This docker-compose file is an example for a setup with a single API Gateway container and a single Elasticsearch container.
# The image name of API Gateway can be set by modifying the .env file when the file is in the working directory or by setting the environment variable APIGW_DOCKER_IMAGE_NAME.
# To use this file run: docker-compose -f apigw-elasticsearch-no-cluster.yml up
# Append -d to run it in detached mode.
# To stop and remove containers, networks, volumes and images created by up run: docker-compose -f apigw-elasticsearch-no-cluster.yml down
version: '3.5'
services:
  apigateway:
    # Image name
    image: ${APIGW_DOCKER_IMAGE_NAME}
    # Container name
    container_name: api-gateway-01
    environment:
      # Name and port of the REST interface of the Elasticsearch container.
      - apigw_elasticsearch_hosts=elasticsearch:9200
      # HTTPS enablement.
      - apigw_elasticsearch_https_enabled=false
      # Username and password for Elasticsearch. As standard leave it blank.
      - apigw_elasticsearch_http_username=
      - apigw_elasticsearch_http_password=
    # Setting for exposing ports to the outside (external port:internal port).
    ports:
      # Server port
      - 5555:5555
      # UI port
      - 9072:9072
    # Needs to be the same network for all containers.
    networks:
      - api-gateway-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    # Elasticsearch settings
    environment:
      # Important when you have several Elasticsearch containers. They need to be in the same network. Should be a different name than in other environments.
      - cluster.name=SAG_EventDataStore
      # The node name. Used for inital master node discovery.
      - node.name=elasticsearch
      # For discovery of all Elasticsearch containers.
      - discovery.seed_hosts=elasticsearch:9300
      # Used for cluster bootstrapping. The mentioned nodes are potential master nodes.
      - cluster.initial_master_nodes=elasticsearch
    ports:
      # REST interface
      - 9240:9200
      # Nodes communication
      - 9340:9300
    networks:
      - api-gateway-network
networks:
  api-gateway-network:
    # For setting a specific network name.
    name: api-gateway-network