<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">renameFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nCW9sZEZpbGVOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJPbGRGaWxlTmFtZSIgKTsKU3RyaW5nCW5ld0ZpbGVOYW1lID0gSURhdGFVdGlsLmdl
dFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJOZXdGaWxlTmFtZSIgKTsKcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOwogCi8vcmVuYW1lIEZpbGUKIFN0cmluZyByZXN1bHQ9IiI7CiBTdHJpbmcgc3Ry
TWVzc2FnZT0iIjsKIFN0cmluZyBkYXRhOwogIAkJdHJ5CgkJewoJCQlSYW5kb21BY2Nlc3NGaWxl
IHJhZj0gbmV3IFJhbmRvbUFjY2Vzc0ZpbGUob2xkRmlsZU5hbWUsInIiKTsKCQkJRmlsZU91dHB1
dFN0cmVhbSBmb3M9bmV3IEZpbGVPdXRwdXRTdHJlYW0obmV3RmlsZU5hbWUpOwoJCQlQcmludFdy
aXRlciBvdXQgPSBuZXcgUHJpbnRXcml0ZXIoZm9zLHRydWUpOwoJCQl3aGlsZSgoZGF0YT1yYWYu
cmVhZExpbmUoKSkhPW51bGwpCgkJCXsKCQkJCW91dC5wcmludGxuKGRhdGEpOwoJCQl9CgkJCW91
dC5mbHVzaCgpOwoJCSAgICAgICAgb3V0LmNsb3NlKCk7CgkJCXJhZi5jbG9zZSgpOwoJCQlmb3Mu
Y2xvc2UoKTsKCQkJRmlsZSBmaWxlPSBuZXcgRmlsZShvbGRGaWxlTmFtZSk7CgkJCXJlc3VsdD0i
VCI7CgkJfQoJCWNhdGNoKEV4Y2VwdGlvbiBlKQoJCXsKCQkJcmVzdWx0PSJGIjsKCQkJc3RyTWVz
c2FnZT1lLmdldE1lc3NhZ2UoKTsKCQl9CiAKLy8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxp
bmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpJRGF0YVV0aWwucHV0KCBwaXBlbGlu
ZUN1cnNvcl8xLCAiU3RhdHVzIiwgcmVzdWx0KTsKSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJz
b3JfMSwgIk1lc3NhZ2UiLCBzdHJNZXNzYWdlICk7CnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgp
OwoK</value>
</Values>
