<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getAmdocsFaultCode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlmYXVsdFN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiZmF1
bHRTdHJpbmciICk7DQppbnQgc3RhcnRJZHggPSBmYXVsdFN0cmluZy5pbmRleE9mKCIoIik7DQpp
bnQgZW5kSWR4ID0gZmF1bHRTdHJpbmcuaW5kZXhPZigiKSIpOw0KU3RyaW5nIGZhdWx0Q29kZSA9
ICIyIjsNCnRyeXsNCglmYXVsdENvZGUgPSBmYXVsdFN0cmluZy5zdWJzdHJpbmcoc3RhcnRJZHgr
MSwgZW5kSWR4KTsNCn0gY2F0Y2ggKEV4Y2VwdGlvbiBlKXsNCglmYXVsdENvZGUgPSAiMiI7DQp9
DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwgImZhdWx0Q29kZSIsIGZhdWx0Q29kZSAp
Ow0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
