<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">doThreadInvoke</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5n
CXNlcnZpY2VOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzZXJ2
aWNlTmFtZSIgKTsKSURhdGEJaW5wdXREYXRhID0gSURhdGFVdGlsLmdldElEYXRhKCBwaXBlbGlu
ZUN1cnNvciwgImlucHV0RGF0YSIgKTsKTlNOYW1lIHRhcmdldFNlcnZpY2VOU05hbWUgPSBOU05h
bWUuY3JlYXRlIChzZXJ2aWNlTmFtZSk7Cgp0cnl7CglTZXJ2aWNlLmRvVGhyZWFkSW52b2tlICh0
YXJnZXRTZXJ2aWNlTlNOYW1lLCBpbnB1dERhdGEpOwoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVD
dXJzb3IsICJvdXRwdXREYXRhIiwgaW5wdXREYXRhICk7Cn0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7
Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfSBmaW5hbGx5ewoJcGlwZWxpbmVDdXJz
b3IuZGVzdHJveSgpOwp9Cg==</value>
</Values>
