<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">truncateDeliverDateTime</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9HZXQgaW5wdXQKICBJRGF0YUN1cnNvciBpZGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKICBE
YXRlIGphdmFEYXRlID0gKERhdGUpIElEYXRhVXRpbC5nZXQoaWRjLCAicmVwbHlEYXRlVGltZSIp
OwogCiAgU3RyaW5nIGRkTU15eXl5ID0gIiI7CiAgU3RyaW5nIGhobW1zcyA9ICIiOyAgCgp0cnl7
IAogICAgRGF0ZUZvcm1hdCBmb3JtYXR0ZXIgPSBuZXcgU2ltcGxlRGF0ZUZvcm1hdCgiZGQtTU0t
eXl5eSIpOwogICAgRGF0ZUZvcm1hdCBmb3JtYXR0ZXIxID0gbmV3IFNpbXBsZURhdGVGb3JtYXQo
IkhIOm1tOnNzIik7CgogICAgZGRNTXl5eXkgPSBmb3JtYXR0ZXIuZm9ybWF0KChuZXcgRGF0ZShT
eXN0ZW0uY3VycmVudFRpbWVNaWxsaXMoKSkpKS50b1N0cmluZygpOwogICAgaGhtbXNzID0gZm9y
bWF0dGVyMS5mb3JtYXQoKG5ldyBEYXRlKFN5c3RlbS5jdXJyZW50VGltZU1pbGxpcygpKSkpLnRv
U3RyaW5nKCk7CiAKfWNhdGNoKEV4Y2VwdGlvbiBlKXsKICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNl
cHRpb24oZS5nZXRNZXNzYWdlKCkpOwp9CgpJRGF0YVV0aWwucHV0KCBpZGMsICJkZE1NeXl5eSIs
IGRkTU15eXl5ICk7CklEYXRhVXRpbC5wdXQoIGlkYywgImhobW1zcyIsIGhobW1zcyApOwoKaWRj
LmRlc3Ryb3koKTsKCg==</value>
</Values>
