<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">fileToString</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgLSBpbgpJRGF0YUN1cnNvciBwYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpT
dHJpbmcJZmlsZU5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwYywgImZpbGVOYW1lIiApOwpT
dHJpbmcgIHRvU3RyaW5nTGlzdCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBjLCAidG9TdHJpbmdM
aXN0IiApOwpTdHJpbmcgIGZpbGVDb250ZW50ID0gbnVsbCwgY2xpbmU7CmJvb2xlYW4gbWtsaXN0
ID0gZmFsc2U7ClZlY3RvciB2ID0gbmV3IFZlY3RvcigpOwpCdWZmZXJlZFJlYWRlciBpbiA9IG51
bGw7ClN0cmluZ1tdIHNjID0gbnVsbDsKCnRyeXsKCWlmKHRvU3RyaW5nTGlzdC5lcXVhbHMoIllF
UyIpKSBta2xpc3QgPSB0cnVlOwoKCWluID0gbmV3IEJ1ZmZlcmVkUmVhZGVyKG5ldyBGaWxlUmVh
ZGVyKGZpbGVOYW1lKSk7CgoJd2hpbGUodHJ1ZSl7CgkJaWYoIChjbGluZSA9IGluLnJlYWRMaW5l
KCkpID09IG51bGwpIGJyZWFrOwoJCQoJCWlmKCBmaWxlQ29udGVudCA9PSBudWxsICkKCQkJaWYo
bWtsaXN0KQoJCQkJdi5hZGQoY2xpbmUpOwoJCQllbHNlCgkJCQlmaWxlQ29udGVudCA9IGNsaW5l
OwoJCWVsc2UKCQkJaWYobWtsaXN0KQoJCQkJdi5hZGQoY2xpbmUpOwoJCQllbHNlewoJCQkJZmls
ZUNvbnRlbnQgPSBmaWxlQ29udGVudCArICJcbiIgKyBjbGluZTsKCQkJfQoJfQoJdHJ5eyAvLyBm
aWxlIGNvbnRlbnRzCgkJc2MgPSBuZXcgU3RyaW5nW3Yuc2l6ZSgpXTsKCQlmb3IoaW50IHggPSAw
OyB4IDwgdi5zaXplKCk7IHgrKykKCQlzY1t4XSA9IChTdHJpbmcpdi5lbGVtZW50QXQoeCk7Cgl9
Y2F0Y2goRXhjZXB0aW9uIGUpe30KfQpjYXRjaChFeGNlcHRpb24gZSl7CgkvLyBkbyBub3RoaW5n
Cn0KZmluYWxseXsgCgl0cnl7CgkJaW4uY2xvc2UoKTsKCX1jYXRjaChFeGNlcHRpb24gZSkKCXt9
Cn0KCi8vIHBpcGVsaW5lIC0gb3V0CmlmKG1rbGlzdCkKCUlEYXRhVXRpbC5wdXQoIHBjLCAiZmls
ZUNvbnRlbnQiLCBzYyApOwplbHNlCglJRGF0YVV0aWwucHV0KCBwYywgImZpbGVDb250ZW50Iiwg
ZmlsZUNvbnRlbnQgKTsKcGMuZGVzdHJveSgpOwo=</value>
</Values>
