<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">endWithStr</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nIGlucHV0ID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNvciwg
ImlucHV0VmFsdWUiKTsKU3RyaW5nIG1hdGNoID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGlu
ZUN1cnNvciwgIm1hdGNoIik7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCmJvb2xlYW4gYiA9
IGlucHV0LmVuZHNXaXRoKG1hdGNoKTsKU3RyaW5nIHJlc3VsdCA9IFN0cmluZy52YWx1ZU9mKGIp
OwoKLy8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOwpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yXzEsICJyZXN1bHQiLHJlc3Vs
dCk7CnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOwo=</value>
</Values>
