<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">dateStrToEpochTime</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5n
CXN0ckRhdGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInN0ckRhdGUi
ICk7ClN0cmluZwlkYXRlVGltZUZvcm1hdCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5l
Q3Vyc29yLCAiZGF0ZVRpbWVGb3JtYXQiICk7Cgp0cnkgewoJU2ltcGxlRGF0ZUZvcm1hdCBmb3Jt
YXR0ZXIgPSBuZXcgU2ltcGxlRGF0ZUZvcm1hdChkYXRlVGltZUZvcm1hdCk7CglEYXRlIGRhdGVP
YmogPSBmb3JtYXR0ZXIucGFyc2Uoc3RyRGF0ZSk7CQoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVD
dXJzb3IsICJlcG9jaFRpbWVNcyIsIExvbmcudG9TdHJpbmcoZGF0ZU9iai5nZXRUaW1lKCkpICk7
CQp9Y2F0Y2ggKEV4Y2VwdGlvbiBleGMpewoJU2VydmVyQVBJLmxvZ0Vycm9yKGV4Yyk7Cgl0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbihleGMudG9TdHJpbmcoKSk7Cn0KCnBpcGVsaW5lQ3Vyc29y
LmRlc3Ryb3koKTs=</value>
</Values>
