<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">dateToStr_java</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewoJRGF0ZSBqYXZh
RGF0ZSA9IChEYXRlKSBJRGF0YVV0aWwuZ2V0KGlkYywgImphdmFEYXRlIik7CglTdHJpbmcgZGF0
ZVRpbWVGb3JtYXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlkYywgImRhdGVUaW1lRm9ybWF0Iik7
CglTaW1wbGVEYXRlRm9ybWF0IHNkZiA9IG5ldyBTaW1wbGVEYXRlRm9ybWF0KGRhdGVUaW1lRm9y
bWF0KTsKCVN0cmluZyBvdXRTdHIgPSBzZGYuZm9ybWF0KGphdmFEYXRlKTsKCUlEYXRhVXRpbC5w
dXQoaWRjLCAic3RyRGF0ZSIsIG91dFN0cik7Cn0gY2F0Y2ggKEV4Y2VwdGlvbiBleGMpIHsKCVNl
cnZlckFQSS5sb2dFcnJvcihleGMpOwoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZXhjLnRv
U3RyaW5nKCkpOwp9CgppZGMuZGVzdHJveSgpOw==</value>
</Values>
