<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">dateToStrArray_java</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgp0cnkgewoJRGF0ZVtdIGph
dmFEYXRlID0gKERhdGVbXSkgSURhdGFVdGlsLmdldE9iamVjdEFycmF5KGlkYywgImphdmFEYXRl
Iik7CglTdHJpbmcgZGF0ZVRpbWVGb3JtYXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlkYywgImRh
dGVUaW1lRm9ybWF0Iik7CglTaW1wbGVEYXRlRm9ybWF0IHNkZiA9IG5ldyBTaW1wbGVEYXRlRm9y
bWF0KGRhdGVUaW1lRm9ybWF0KTsKCVN0cmluZ1tdIG91dFN0ciA9IG5ldyBTdHJpbmdbamF2YURh
dGUubGVuZ3RoXTsKCglmb3IgKGludCBpPTA7IGkgPCBqYXZhRGF0ZS5sZW5ndGg7IGkrKykgewoJ
CW91dFN0cltpXSA9IG5ldyBTdHJpbmcoKTsKCQlvdXRTdHJbaV0gPSBzZGYuZm9ybWF0KGphdmFE
YXRlW2ldKTsKCX0KCglJRGF0YVV0aWwucHV0KGlkYywgInN0ckRhdGUiLCBvdXRTdHIpOwp9IGNh
dGNoIChFeGNlcHRpb24gZXhjKSB7CglTZXJ2ZXJBUEkubG9nRXJyb3IoZXhjKTsKCXRocm93IG5l
dyBTZXJ2aWNlRXhjZXB0aW9uKGV4Yy50b1N0cmluZygpKTsKfQoKaWRjLmRlc3Ryb3koKTs=</value>
</Values>
